name: testapp20131007
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins: # 웹 브라우저에서 '#' 삭제를 위해
    sdk: flutter

  flutter_localizations: # Add this line 국제화에 필요
    sdk: flutter         # Add this line 국제화에 필요

  intl: ^0.18.1
  intl_utils: ^2.8.5
  # windows desktop 를 위해: 아직 불안정.
  firebase_core: ^2.21.0
  firebase_storage: ^11.4.1
  firebase_auth: ^4.11.1
  firebase_ui_auth: ^1.6.5
  # ANDROID, IOS, MACOS, WEB
  firebase_ui_oauth_google: ^1.2.9
  firebase_ui_firestore: ^1.5.9
  # FCM Push message
  firebase_messaging: ^14.7.3
  flutter_local_notifications: ^16.1.0

  #firebase_dynamic_links: ^5.2.0
  #firebase_ui_oauth_apple: ^1.1.1
  cloud_firestore: ^4.12.2
  cloud_functions: ^4.5.3
  sign_in_with_apple: ^5.0.0
  #google_sign_in: ^5.4.0
  #flutterfire_ui: ^0.4.3+20

  # 작은 svg 지원, 큰사이즈 지원안됨(websafe_svg 검토바람)
  flutter_svg: ^2.0.7

  shared_preferences: ^2.2.2
  http_parser: ^4.0.2


  go_router: ^12.1.0

  # https://flutter.github.io/cupertino_icons/
  cupertino_icons: ^1.0.6

  # 현재 시스템 theme 가져온다
  system_theme: ^2.3.1

  # Multi Sliver 를 위해 필요
  sliver_tools: ^0.2.12

  # 단순한 투명 이미지 https://pub.dev/packages/transparent_image
  transparent_image: ^2.0.1

  flutter_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0
  #  Error: The getter 'valueType' isn't defined for the class 'GeneratorProviderDeclaration'.
  # 해결 될 때 까지 아래버전 유지.
  riverpod_generator: ^2.3.5
  # riverpod_lint: ^2.3.3

  # 버블
  #blobs: ^2.0.0


  # url launcher 와 meta 패키지 버전 업 하지 말것, 할경우 검증 후 진행
  #url_launcher: ^6.2.1
  url_launcher_platform_interface: ^2.2.0
  collection: ^1.17.1
  nanoid: ^1.0.0





  # unsplash image
  #unsplash_client: ^2.1.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  share_plus: ^7.2.1
  google_fonts: ^6.1.0
  flex_color_picker: ^3.3.0

  # WEB 지원안함
  cached_network_image: ^3.3.0

  uuid: ^3.0.5

  #enum_to_string: ^2.0.1

  # 임의의 문장과 단락 생성, 임시 아이템 제목 생성 시 필요
  flutter_lorem: ^2.0.0

  # 사용: 현재장치정보: IOS, Android, MacOS, Linux, Windows
  # lib/project_util/util_board/device_info.dart
  universal_platform: ^1.0.0+1
  universal_io: ^2.2.2
  # Local 언어 등
  #devicelocale: ^0.6.0



  timeago: ^3.6.0
  email_validator: ^2.1.17
  file_picker: ^6.1.1
  animated_text_kit: ^4.2.2

  # ANDROID, IOS, WEB
  video_player: ^2.8.1
  image_picker: ^1.0.4
  image: ^4.1.3
  uni_links: ^0.5.1
  # ---------------------


  badges: ^3.1.2



  flutter_advanced_switch: ^3.0.1

  # 이미지 슬라이더
  flutter_image_slider: ^0.0.2
  # FONT ICONS
  font_awesome_flutter: ^10.6.0

  # 점선
  dotted_decoration: ^2.0.0

  equatable: ^2.0.5

  # MicroSoft Icons
  # https://github.com/microsoft/fluentui-system-icons/blob/master/icons_regular.md
  fluentui_system_icons: ^1.1.221

  # CORS Web image: android, ios, web
  #image_network: ^2.5.2


  # Drag & Drop : Web 에서 _offset != null 오류 발생
  # https://github.com/MixinNetwork/flutter-plugins/issues/103
  # ANDROID, MACOS, WEB, WINDOWS
  #desktop_drop: ^0.4.1

  #super_drag_and_drop: ^0.4.0
  #flutter_dropzone: ^3.0.5

  cross_file: ^0.3.3+6
  #fab_circular_menu: ^1.0.2

  # 머티리얼 디자인에서 반응형 레이아웃을 구현하기 위한 Flutter 패키지.
  adaptive_components: ^0.0.9


  reorderable_grid: ^1.0.9
  sprung: ^3.0.1
  photo_view: ^0.14.0

  # 아래 두 패지는 상호 버전 의존성이 있음 업데이트 시 주의
  spreadsheet_decoder: ^2.2.0
  syncfusion_flutter_xlsio: ^23.1.43

  flutter_sticky_header: ^0.6.5

  context_menus: ^1.0.2
  auto_size_text: ^3.0.0

  mime: ^1.0.4

  loading_animation_widget: ^1.2.0+4
  #algolia: ^1.1.2
  algolia_helper_flutter: ^0.5.0
  infinite_scroll_pagination: ^4.0.0
  form_field_validator: ^1.1.0
  form_validator: ^2.1.1
  # 주문 옵션 추후 검토 할 것
  #dropdown_below: ^1.0.3

  flutter_rating_bar: ^4.0.1
  responsive_ui: ^3.0.1
  percent_indicator: ^4.2.3
  # 웹에서 # 삭제
  url_strategy: ^0.2.0

  archive: ^3.4.8
  path: ^1.8.3
  # 파일 다운로드를 위해 필요: 크로스 플랫폼
  dio: ^5.3.3
  # 모바일 용
  path_provider: ^2.1.1
  #translator: ^0.1.7
  flutter_animate: ^4.2.0+1
  flutter_staggered_grid_view: ^0.7.0

  # html_editor_enhanced: ^2.5.1
  # 위 html editor 로 입력된 내용을 표시하기 위한 패키지, html 코드 위젯
  #flutter_widget_from_html: ^0.10.3
  #flutter_widget_from_html_core: ^0.10.4

  # flutter web 에서 Webview 를 사용할 수 있도록 하는 패키지
  # webview_flutter_platform_interface: ^2.5.0
  # webview_flutter_web: ^0.2.2+1
  # rich_text_editor_controller: ^0.0.4
  # appflowy_editor: ^1.2.4
  #webview_flutter: ^4.4.2
  #webview_flutter_web: ^0.2.2+3
  webview_flutter_platform_interface: ^2.6.0
  #webview_pro_platform_interface: ^1.8.1+2
  # text editor
  fleather: ^1.10.0
  top_snackbar_flutter: ^3.1.0
  # 음성을 text로 변환
  speech_to_text: ^6.4.0
  permission_handler: ^11.0.1
  # microphone: ^0.1.0
  avatar_glow: ^2.0.2
  flutter_stripe: ^9.5.0+1
  flutter_stripe_web: ^4.5.0
  http: ^1.1.0
  dart_openai: ^4.0.0
  envied: ^0.5.1
  html_unescape: ^2.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  #add new -------
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  connectivity_plus: ^5.0.1
  envied_generator: ^0.5.1


flutter:
  uses-material-design: true
  generate: true # Add this line 국제화에 필요



flutter_intl:
  enabled: true


